[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[project]
name = "wsjrdp2027"
version = "0.0.1"
description = "Helpers for wsjrdp_scripts"
readme = "README.md"
authors = [
    { name = "David Fritzsche", email = "david.fritzsche@worldscoutjamboree.de" }
]
requires-python = ">=3.13"
dependencies = [
    "humanfriendly>=10.0",
    "jinja2>=3.1.6",
    "paramiko<4",
    "psycopg[binary]>=3.2.9",
    "pyyaml>=6.0.2",
    "schwifty>=2025.9.0",
    "sepaxml>=2.7.0",
    "sshtunnel>=0.4.0",
    "typst>=0.14",
]

[dependency-groups]
mypy = [
    "types-humanfriendly>=10.0.1.20250319",
]
pytest = [
    "pytest>=8.4.1",
    "time-machine>=2.17.0",
]
