is_production: false

use_ssh_tunnel: false

db_host: "localhost"
db_port: 5432
db_username: "hitobito"
db_password: "hitobito"
db_name: "hitobito_development"

hitobito_url: "http://localhost:3000"

smtp_server: "localhost"
smtp_port: 1025

mail_accounts:
  anmeldung@worldscoutjamboree.de:
    smtp_server: localhost
    smtp_port: 1025
  unit-management@worldscoutjamboree.de:
    smtp_server: localhost
    smtp_port: 1025
